#!/bin/bash
make -f mcpi.mak
make -f mcsph.mak
make -f mcparab.mak
make -f mcbell.mak
make -f mcsin.mak
make -f mccos.mak
make -f binom.mak
make -f poischi.mak
make -f uintchi.mak
make -f etauschi.mak
make -f etausgen.mak
make -f etausraw.mak
make -f etaustim.mak
make -f etauspat.mak
make -f etausdots.mak
make -f etausnorm.mak
make -f tstetaus.mak
make -f ranwlk.mak
make -f pwrball.mak
make -f captcha.mak
make -f etausencr.mak
make -f genalfa.mak
make -f gendna.mak
make -f pair.mak
